In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
!nvidia-smi

Fri May 21 21:22:42 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   55C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
!pip install tensorflow-gpu


     |████████████████████████████████| 454.3MB 35kB/s 
     |████████████████████████████████| 471kB 44.8MB/s 
     |████████████████████████████████| 4.0MB 41.1MB/s 
     |████████████████████████████████| 4.0MB 47.5MB/s 
     |████████████████████████████████| 1.2MB 46.2MB/s 
     |████████████████████████████████| 6.0MB 42.4MB/s 
     |████████████████████████████████| 4.9MB 48.6MB/s 
ERROR: tensorflow 2.4.1 has requirement gast==0.3.3, but you'll have gast 0.4.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement grpcio~=1.32.0, but you'll have grpcio 1.34.1 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement h5py~=2.10.0, but you'll have h5py 3.1.0 which is incompatible.
ERROR: tensorflow 2.4.1 has requirement tensorflow-estimator<2.5.0,>=2.4.0, but you'll have tensorflow-estimator 2.5.0 which is incompatible.
  Found existing installation: tensorflow-estimator 2.4.0
    Uninstalling tensorflow-estimator-2.4.0:
      Successfully uninstalled tensorflow-estim

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
train=pd.read_csv('/content/drive/MyDrive/dataset/Dataset2012/train_change_dete.csv',encoding='utf-8')
test=pd.read_csv('/content/drive/MyDrive/dataset/Dataset2012/test_change_dete.csv',encoding='utf-8')

In [ ]:
len(train)

1999

In [ ]:
import cv2
train_data=[]
train_labels=[]

test_data=[]
test_labels=[]

for i in range(len(train)):
    print(train['Images'][i])
    image = cv2.imread(train['Images'][i])
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image = cv2.resize(image, (224, 224))
    train_data.append(image)
    if(train['label'][i]=='No Change'):
        train_labels.append(0)
    elif(train['label'][i]=='Slight Change'):
        train_labels.append(1)
    else:
        train_labels.append(2)

train_data=np.array(train_data)/255.0
train_labels=np.array(train_labels)




In [ ]:
for j in range(len(test)):
    
    image = cv2.imread(train['Images'][j])
    image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
    image = cv2.resize(image, (224, 224))
    test_data.append(image)
    if(train['label'][j]=='No Change'):
        test_labels.append(0)
    elif(train['label'][j]=='Slight Change'):
        test_labels.append(1)
    else:
        test_labels.append(2)



test_data=np.array(test_data)/255.0
test_labels=np.array(test_labels)

In [ ]:
print(test_data)

[[[[0.21176471 0.24313725 0.18431373]
   [0.09803922 0.12941176 0.07058824]
   [0.10980392 0.14117647 0.08235294]
   ...
   [0.21960784 0.25098039 0.29019608]
   [0.25882353 0.30588235 0.36078431]
   [0.2        0.25098039 0.31372549]]

  [[0.15294118 0.18431373 0.1254902 ]
   [0.09019608 0.12156863 0.0627451 ]
   [0.10588235 0.1372549  0.07843137]
   ...
   [0.45098039 0.48627451 0.52156863]
   [0.48627451 0.52941176 0.58039216]
   [0.41960784 0.46666667 0.53333333]]

  [[0.1254902  0.15686275 0.09803922]
   [0.08235294 0.11372549 0.05490196]
   [0.05490196 0.08627451 0.02745098]
   ...
   [0.45098039 0.47843137 0.51372549]
   [0.5372549  0.57647059 0.62745098]
   [0.53333333 0.58039216 0.64313725]]

  ...

  [[0.52156863 0.51764706 0.49803922]
   [0.50196078 0.49411765 0.47843137]
   [0.49411765 0.49019608 0.47058824]
   ...
   [0.40392157 0.34117647 0.31372549]
   [0.41176471 0.35294118 0.3254902 ]
   [0.46666667 0.40392157 0.37647059]]

  [[0.50196078 0.50196078 0.47058824]
   [0.4

In [ ]:
print(train_labels)

[0 0 0 ... 1 1 1]


In [ ]:
print(test_data)

[[[[0.21176471 0.24313725 0.18431373]
   [0.09803922 0.12941176 0.07058824]
   [0.10980392 0.14117647 0.08235294]
   ...
   [0.21960784 0.25098039 0.29019608]
   [0.25882353 0.30588235 0.36078431]
   [0.2        0.25098039 0.31372549]]

  [[0.15294118 0.18431373 0.1254902 ]
   [0.09019608 0.12156863 0.0627451 ]
   [0.10588235 0.1372549  0.07843137]
   ...
   [0.45098039 0.48627451 0.52156863]
   [0.48627451 0.52941176 0.58039216]
   [0.41960784 0.46666667 0.53333333]]

  [[0.1254902  0.15686275 0.09803922]
   [0.08235294 0.11372549 0.05490196]
   [0.05490196 0.08627451 0.02745098]
   ...
   [0.45098039 0.47843137 0.51372549]
   [0.5372549  0.57647059 0.62745098]
   [0.53333333 0.58039216 0.64313725]]

  ...

  [[0.52156863 0.51764706 0.49803922]
   [0.50196078 0.49411765 0.47843137]
   [0.49411765 0.49019608 0.47058824]
   ...
   [0.40392157 0.34117647 0.31372549]
   [0.41176471 0.35294118 0.3254902 ]
   [0.46666667 0.40392157 0.37647059]]

  [[0.50196078 0.50196078 0.47058824]
   [0.4

In [ ]:
print(test_labels)

[0 0 0 ... 0 2 1]


In [ ]:
from tensorflow.keras.layers import Input, Lambda, Dense, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.applications.vgg16 import VGG16
from tensorflow.keras.applications.vgg16 import preprocess_input
from tensorflow.keras.preprocessing import image
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.models import Sequential
import numpy as np
from glob import glob
import matplotlib.pyplot as plt

In [ ]:
IMAGE_SIZE = [224, 224]
vgg = VGG16(input_shape=IMAGE_SIZE + [3], weights='imagenet', include_top=False)
for layer in vgg.layers:
  layer.trainable = False
x = Flatten()(vgg.output)
prediction = Dense(3, activation='softmax')(x)
model = Model(inputs=vgg.input, outputs=prediction)
model.summary()
model.compile(
  loss='sparse_categorical_crossentropy',
  optimizer='adam',
  metrics=['accuracy']
)

Model: "model_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0   

In [ ]:
from keras.callbacks import ModelCheckpoint, LearningRateScheduler, EarlyStopping, ReduceLROnPlateau, TensorBoard
earlyStopping = EarlyStopping(monitor='val_loss',
                              min_delta=0,
                              patience=3,
                              verbose=1)

callback_early_stop_reduceLROnPlateau=[earlyStopping]


EPOCHS = 5
BS = 1
progess = model.fit(train_data,train_labels, batch_size=BS,epochs=EPOCHS, callbacks=callback_early_stop_reduceLROnPlateau,validation_split=.05)

Epoch 1/5
1899/1899 [==============================] - 868s 457ms/step - loss: 1.7182 - accuracy: 0.8515 - val_loss: 2.1382 - val_accuracy: 0.9200
Epoch 2/5
1899/1899 [==============================] - 858s 452ms/step - loss: 1.6094 - accuracy: 0.8763 - val_loss: 2.6362 - val_accuracy: 0.9200
Epoch 3/5
1899/1899 [==============================] - 840s 442ms/step - loss: 1.6565 - accuracy: 0.8899 - val_loss: 0.9661 - val_accuracy: 0.7400
Epoch 4/5
1899/1899 [==============================] - 838s 441ms/step - loss: 1.1987 - accuracy: 0.9073 - val_loss: 1.8393 - val_accuracy: 0.9200
Epoch 5/5
1899/1899 [==============================] - 836s 440ms/step - loss: 1.4031 - accuracy: 0.9042 - val_loss: 1.0936 - val_accuracy: 0.8600


In [ ]:
predictions=model.predict(test_data)


In [ ]:
y_classes = predictions.argmax(axis=-1)


In [ ]:
from sklearn.metrics import classification_report,confusion_matrix, accuracy_score
correct_count = 0.0
accuracy=accuracy_score(test_labels,y_classes)
# for i in range(len(test_labels)):
#     if predictions[i] == test_labels[i]:
#         correct_count += 1.0
# accuracy = correct_count/float(len(test_labels))
print("Accuracy:", accuracy)
print(classification_report(test_labels, y_classes))
print(confusion_matrix(test_labels, y_classes))

Accuracy: 0.9645641389085755
              precision    recall  f1-score   support

           0       0.91      0.97      0.94       207
           1       0.99      0.98      0.98      1159
           2       0.65      0.58      0.61        45

    accuracy                           0.96      1411
   macro avg       0.85      0.84      0.85      1411
weighted avg       0.96      0.96      0.96      1411

[[ 201    5    1]
 [  12 1134   13]
 [   7   12   26]]
